### PR TITLE
Disable misc.xml generation

### PR DESCRIPTION
**Pull request by davidkzeng**
See https://github.com/Addepar/AMP/pull/21490 for details.

### CODE REVIEW

**Comment by liuyang-li** [comment]
@davidzeng-add , it might be preferable to change the post processing script and just check in a misc file that we like instead of changing Buck itself.

At the same time, both @jiangty-addepar and @liuyang-li would be happy to work with you on that;-).

**Comment by bdworth** [comment]
>  it might be preferable to change the post processing script and just check in a misc file that we like instead of changing Buck itself.

That might be fine for later, but we've literally been waiting over a year for this. Are you opposed enough to this approach to want to block it as is?

**Comment by bdworth** [comment]
We shouldn't need this anymore after the latest changes to https://github.com/Addepar/AMP/pull/21490

**Pull request closed without merging**
